import { getCurrentLanguage } from "../../i18n/i18n"

const currentLang = getCurrentLanguage()
const langDicts = import.meta.glob<Record<string, string>>("../../meta/*.json", { eager: true })
const langDict = langDicts[`../../meta/${currentLang}.json`];

function TextConfig() {
    return {
        hi: langDict.hi,
        appName: langDict.appName,
        login: langDict.login,
        register: langDict.register,
        logout: langDict.logout,
        email: langDict.email,
        password: langDict.password,
        name: langDict.name,
        doLogin: langDict.doLogin,
        doRegister: langDict.doRegister,
        haveAccount: langDict.haveAccount,
        noAccount: langDict.noAccount,
        myPosters: langDict.myPosters,
        newPoster: langDict.newPoster,
        templates: langDict.templates,
        open: langDict.open,
        clone: langDict.clone,
        remove: langDict.remove,
        save: langDict.save,
        saved: langDict.saved,
        addText: langDict.addText,
        addRect: langDict.addRect,
        addCircle: langDict.addCircle,
        addImage: langDict.addImage,
        uploadImage: langDict.uploadImage,
        print: langDict.print,
        exportPng: langDict.exportPng,
        layers: langDict.layers,
        props: langDict.props,
        fill: langDict.fill,
        text: langDict.text,
        fontSize: langDict.fontSize,
        width: langDict.width,
        height: langDict.height,
        format: langDict.format,
        posterName: langDict.posterName,
        toFront: langDict.toFront,
        toBack: langDict.toBack,
        authRequired: langDict.authRequired,
        navHome: langDict.navHome,
        navGallery: langDict.navGallery,
        navProfile: langDict.navProfile,
        dashboard: langDict.dashboard,
        welcomeBack: langDict.welcomeBack,
        statsPosters: langDict.statsPosters,
        statsAssets: langDict.statsAssets,
        statsTemplates: langDict.statsTemplates,
        openGallery: langDict.openGallery,
        memberSince: langDict.memberSince,
        notAuthorized: langDict.notAuthorized,
        goLogin: langDict.goLogin,
        selectBlockHint: langDict.selectBlockHint,
        blockText: langDict.blockText,
        blockFill: langDict.blockFill,
        canvasBg: langDict.canvasBg,
        blockFontSize: langDict.blockFontSize,
        blockWidth: langDict.blockWidth,
        blockHeight: langDict.blockHeight,
        moveBlockUp: langDict.moveBlockUp,
        moveBlockDown: langDict.moveBlockDown,
        deleteBlock: langDict.deleteBlock,
        posterNameLabel: langDict.posterNameLabel,
        backToGallery: langDict.backToGallery,
        saveError: langDict.saveError,
        loading: langDict.loading,
        importHtml: langDict.importHtml,
        importBadge: langDict.importBadge,
        importHtmlTitle: langDict.importHtmlTitle,
        importTabCode: langDict.importTabCode,
        importTabFile: langDict.importTabFile,
        htmlSnippetLabel: langDict.htmlSnippetLabel,
        loadSample: langDict.loadSample,
        dropzoneHint: langDict.dropzoneHint,
        dropzoneOrBrowse: langDict.dropzoneOrBrowse,
        importReplaceBlocks: langDict.importReplaceBlocks,
        importResizeCanvas: langDict.importResizeCanvas,
        cancelBtn: langDict.cancelBtn,
        importBtn: langDict.importBtn,
        components: langDict.components,
        canvasHint: langDict.canvasHint,
        radius: langDict.radius,
        opacity: langDict.opacity,
    }
}
export default TextConfig()